;;; test-integrations.el --- Opt-in helper regression checks -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(add-to-list 'load-path (file-name-directory (or load-file-name buffer-file-name)))
(require 'gruber-darker-bell)
(require 'gruber-darker-org)
(defvar treemacs-icons-dired-mode nil)

;; Optional dependency snapshot or installed package directories supplied by
;; the caller.  Never read the user's init or connect to a daemon.
(when-let ((directory (getenv "GRUBER_TEST_DEPS")))
  (dolist (path (directory-files directory t "^[^.]"))
    (when (file-directory-p path) (add-to-list 'load-path path))))

(ert-deftest gruber-bell-restores-settings-and-is-repeatable ()
  (let ((ring-bell-function #'ignore)
        (visible-bell nil)
        (gruber-darker-bell-mode nil)
        (gruber-darker-bell--saved-settings nil))
    (gruber-darker-bell-mode 1)
    (gruber-darker-bell-mode 1)
    (should (eq ring-bell-function #'gruber-darker-bell))
    (gruber-darker-bell-mode -1)
    (should (eq ring-bell-function #'ignore))
    (should-not visible-bell)))

(ert-deftest gruber-bell-cleans-remaps-and-tolerates-killed-buffer ()
  (let (cleanup)
    (cl-letf (((symbol-function 'run-with-timer)
               (lambda (_seconds _repeat function &rest _args)
                 (setq cleanup function))))
      (with-temp-buffer
        (gruber-darker-bell)
        (should face-remapping-alist)
        (funcall cleanup)
        (should-not face-remapping-alist)
        (gruber-darker-bell))
      ;; This is the second callback; its originating buffer has been killed.
      (should-not (funcall cleanup)))))

(ert-deftest gruber-org-special-tags-and-source-exclusions ()
  (let ((org-font-lock-set-keywords-hook org-font-lock-set-keywords-hook)
        (contents "* TODO Heading\n- [X] completed\nText #project @person\n#+begin_src text\n#literal @literal\n#+end_src\n"))
    (gruber-darker-org-config)
    (gruber-darker-org-config)
    (should (= 1 (cl-count #'gruber-darker-enable-org-fontification
                           org-font-lock-set-keywords-hook)))
    (with-temp-buffer
      (insert contents)
      (org-mode)
      (font-lock-ensure)
      (dolist (pair '(("#project" . gruber-darker-org-hash-tag)
                      ("@person" . gruber-darker-org-at-tag)))
        (goto-char (point-min))
        (search-forward (car pair))
        (let ((face (get-text-property (1- (point)) 'face)))
          (should (memq (cdr pair) (if (listp face) face (list face))))))
      (goto-char (point-min))
      (search-forward "#literal")
      (let ((face (get-text-property (1- (point)) 'face)))
        (should-not (memq 'gruber-darker-org-hash-tag
                          (if (listp face) face (list face)))))
      (should (equal contents (buffer-string))))))

(ert-deftest gruber-treemacs-icons-and-layout-are-repeatable ()
  (skip-unless (and (locate-library "treemacs") (locate-library "nerd-icons")))
  (require 'gruber-darker-treemacs)
  (gruber-darker-treemacs-config)
  (let ((count (length treemacs--themes)))
    (gruber-darker-treemacs-config)
    (should (= count (length treemacs--themes))))
  (dolist (name '("gruber-atom" "gruber-colors"))
    (let ((theme (treemacs--find-theme name)))
      (should theme)
      (dolist (extension '(root-open dir-closed "py" "org" "elc"))
        (should (gethash extension (treemacs-theme->gui-icons theme)))
        (should (stringp (gethash extension (treemacs-theme->tui-icons theme)))))))
  (let ((inherit (face-attribute 'treemacs-file-face :inherit nil)))
    (with-temp-buffer
      (gruber-darker-setup-tab-width)
      (gruber-darker-setup-line-spacing)
      (gruber-darker-enable-treemacs-variable-pitch-labels)
      (let ((count (length face-remapping-alist)))
        (gruber-darker-enable-treemacs-variable-pitch-labels)
        (should (= count (length face-remapping-alist))))
      (should (= tab-width 1))
      (should (= line-spacing gruber-darker-treemacs-line-spacing))
      (should (assq 'treemacs-file-face face-remapping-alist)))
    (should (equal inherit (face-attribute 'treemacs-file-face :inherit nil)))))

(ert-deftest gruber-dired-icon-tab-width-is-local-and-restored ()
  (skip-unless (and (locate-library "treemacs") (locate-library "nerd-icons")))
  (require 'gruber-darker-treemacs)
  (with-temp-buffer
    (setq-local tab-width 6)
    (let ((treemacs-icons-dired-mode t))
      (gruber-darker-fix-treemacs-icons-dired-mode)
      (gruber-darker-fix-treemacs-icons-dired-mode)
      (should (= tab-width 1)))
    (let ((treemacs-icons-dired-mode nil))
      (gruber-darker-fix-treemacs-icons-dired-mode)
      (should (= tab-width 6)))))

;;; test-integrations.el ends here
